name: Is Empty
description: Outputs whether automated releases should be skipped since the changelog is empty
inputs:
  yaml:
    description: Path to changelog.yaml
    required: false
    default: changelog.yaml
outputs:
  is-empty:
    description: Returns `true` if next release should not be automated
runs:
  using: docker
  image: ../Dockerfile
  args:
    - --yaml
    - ${{ inputs.yaml }}
    - is-empty
