name: Validate markdown
description: Validates a changelog in markdown format and prints errors if the changelog is invalid
inputs:
  markdown:
    description: Path to CHANGELOG.md to validate
    required: false
    default: CHANGELOG.md
  exit-code:
    description: Exit code when errors are found
    required: false
    default: "1"
outputs:
  valid:
    description: Returns `true` if the changelog is valid
runs:
  using: docker
  image: ../Dockerfile
  args:
    - validate-markdown
    - --markdown
    - ${{ inputs.markdown }}
    - --exit-code
    - ${{ inputs.exit-code }}
