name: Update markdown
description: Incorporates the contents of changelog.yaml as a new version header in CHANGELOG.md
inputs:
  yaml:
    description: Path to changelog.yaml
    required: false
    default: changelog.yaml
  markdown:
    description: Path to CHANGELOG.md to update
    required: false
    default: CHANGELOG.md
  version:
    description: Version to stamp in the changelog section header (no version header if omitted)
    required: false
    default: ""
runs:
  using: docker
  image: ../Dockerfile
  args:
    - --yaml
    - ${{ inputs.yaml }}
    - update-markdown
    - --markdown
    - ${{ inputs.markdown }}
    - --version
    - ${{ inputs.version }}
