name: Link dependencies
description: Attempts to add links to the original changelogs for dependency bumps in changelog.yaml. The link is computed automatically when the dependency name is a full route or it's got from a dictionary file when present.
inputs:
  yaml:
    description: Path to changelog.yaml
    required: false
    default: changelog.yaml
  dictionary:
    description: Link dependency changelogs with the mappings in this dictionary
    required: false
    default: ""
runs:
  using: docker
  image: ../Dockerfile
  args:
    - --yaml
    - ${{ inputs.yaml }}
    - link-dependencies
    - --dictionary
    - ${{ inputs.dictionary }}
