name: Next Version
description: Compute next version according to changelog.yaml and semver conventions
inputs:
  yaml:
    description: Path to changelog.yaml
    required: false
    default: changelog.yaml
  git-root:
    description: Path to the root of the git repository to source tags from
    required: false
    default: "."
  tag-prefix:
    description: Get current version from latest semver tag matching this prefix
    required: false
    default: ""
  output-prefix:
    description: The prefix to prepend when printing the output version
    required: false
    default: "v"
outputs:
  next-version:
    description: Semver next version, with leading v
runs:
  using: docker
  image: ../Dockerfile
  args:
    - --yaml
    - ${{ inputs.yaml }}
    - next-version
    - --git-root
    - ${{ inputs.git-root }}
    - --tag-prefix
    - ${{ inputs.tag-prefix }}
    - --output-prefix
    - ${{ inputs.output-prefix }}
